#!/usr/bin/env python3
from trollfactory import factory


if __name__ == '__main__':
    person = factory.Person('pl_PL', static_properties={
        'sex': {'sex': 'male'},
        'birthdate': {'birth_day': 10, 'age': 25, 'birth_month': 10},
    })
    person.generate()

    print(person.person)